In [13]:
import numpy as np
a = np.arange(11,20)

In [14]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
a = a.reshape(3,3)
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
result = a+10

a(3,3)
(1,)
(3,3)


In [19]:
result

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [30]:
b = np.array((
    [1,2,3]
))


a (3,3)
b(3,1)
(3,3)


In [21]:
result = a+b
result

array([[12, 14, 16],
       [15, 17, 19],
       [18, 20, 22]])

In [25]:
b= np.array((
    [1],[2],[3]
))

a(3,3)
b(3,1)
(3,3)

```
# This is formatted as code
```



In [26]:
result = a+b

In [27]:
result

array([[12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])