In [1]:
import numpy as np

In [2]:
a= np.array((
    [10,20,30,40],
    [50,60,70,80],
    [90,10,110,120]
))

In [6]:
a[1,:4]

array([50, 60, 70, 80])

In [7]:
a[:2,:4]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
a[:3,3]

array([ 40,  80, 120])

In [9]:
a[1,] = [1,2,3,4]

In [10]:
a

array([[ 10,  20,  30,  40],
       [  1,   2,   3,   4],
       [ 90,  10, 110, 120]])