In [1]:
import numpy as np


In [6]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
c=np.eye(5,5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
d = np.full(8,7)
d

array([7, 7, 7, 7, 7, 7, 7, 7])

In [40]:
e = np.random.randint(10,99,size = 12)
e = e.reshape(3,4)
e


array([[15, 45, 77, 19],
       [63, 69, 95, 62],
       [15, 98, 53, 45]])

In [34]:
f = np.arange(5,50, step =5)
f

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [39]:
f = f.reshape((3,3))
f

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])