In [1]:
import numpy as np


In [3]:
a= np.arange(1,13)

In [7]:
 b = a.reshape(3,4)
 b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
c = a.reshape(2,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**Flatten**

In [9]:
c1 = c.flatten()
c1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
c1[6] = 140
c1

array([  1,   2,   3,   4,   5,   6, 140,   8,   9,  10,  11,  12])

In [11]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**No changes occur in original array**

**Ravel**

In [12]:
c2 = c.ravel()
c2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
c2[8] = 50
c2

array([ 1,  2,  3,  4,  5,  6,  7,  8, 50, 10, 11, 12])

In [14]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8, 50, 10, 11, 12]])

**Changes occur in original array**

**By flatten**

In [16]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1 = arr.flatten()
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**By ravel**

In [22]:
arr2 = arr.ravel()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2[6] = 52

In [24]:
arr2

array([ 1,  2,  3,  4,  5,  6, 52,  8,  9])

In [25]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [52,  8,  9]])