In [1]:
import numpy as np

In [7]:
a =np.arange(1,6)

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
b = np.arange(6,11)

In [10]:
b

array([ 6,  7,  8,  9, 10])

In [11]:
print(a+b)

[ 7  9 11 13 15]


In [12]:
print(a-b)

[-5 -5 -5 -5 -5]


In [13]:
print(a*b)

[ 6 14 24 36 50]


In [18]:
print(a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [21]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [22]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [23]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [25]:
c = np.array((
    [1,10,89,45,32]
)
)

In [26]:
f = (c*9/5)+32
f

array([ 33.8,  50. , 192.2, 113. ,  89.6])